services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  photon:
    build:
      context: ./apps/photon
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "2322:2322"
    volumes:
      - ./apps/photon/photon_data:/app/photon_data
    networks:
      - app-network
  api:
    build:
      context: ./apps/api
      dockerfile: Api/Dockerfile
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=db;Username=user;Password=password
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://api:8080/api
    depends_on:
      - api
    ports:
      - "5173:80"
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge
