services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app-network
  
  db-test:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_DB: db-test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata_test:/var/lib/postgresql/data
    networks:
      - app-network

  photon:
    build:
      context: ./apps/photon
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "2322:2322"
    volumes:
      - ./apps/photon/photon_data:/app/photon_data
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge
