name: Web CI

on:
  push:
    paths:
      - "apps/web/**"
      - ".github/workflows/web.yml"
  pull_request:
    paths:
      - "apps/web/**"
      - ".github/workflows/web.yml"

jobs:
  check:
    name: Check and test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Enable corepack (pnpm)
        run: corepack enable

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm run type-check

      - name: Prettier format check
        run: pnpm prettier --check src/

      - name: ESLint (no fix)
        run: pnpm eslint . --max-warnings=0

      - name: Run tests
        run: pnpm test
